#ifndef SYSTEM_STATE_H
#define SYSTEM_STATE_H

enum SystemState {
    STATE_BOOT,
    STATE_WIFI_CONNECTING,
    STATE_TIME_SYNC,
    STATE_IDLE,
    STATE_PRE_SEHRI_ARMED,
    STATE_PRE_SEHRI_RINGING,
    STATE_SEHRI_RINGING,
    STATE_IFTAR_RINGING,
    STATE_PRAYER_BEEP,
    STATE_PARTIAL_ACK,
    STATE_ALL_ACK,
    STATE_OTA_MODE,
    STATE_ERROR
};

#endif
